name: Create .env with Supabase secrets

on:
  push:
    branches:
      - main

jobs:
  create-env:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Create .env file
        run: |
          touch .env
          echo "SECRET_SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SECRET_SUPABASE_SERVICE_ROLE_KEY }}" > .env
          echo "SECRET_SUPABASE_URL=${{ secrets.SECRET_SUPABASE_URL }}" >> .env
