name: Prettier

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          persist-credentials: false
      - run: npm i prettier-plugin-svelte
      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          dry: True
          prettier_options: --check
          github_token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
