name: Prettier Format
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  format:
    runs-on: ubuntu-latest
    name: prettier format
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"    
      - name: Prettier Action
      - uses: creyD/prettier_action@v4.3
        with:
          dry: true
          prettier_options: --check
      
